"use client";

import { useState, useMemo, Suspense } from "react";
import { useStore } from "@/lib/store";
import { useSearchParams } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import Link from "next/link";
import {
  Plus,
  Trash2,
  FlaskConical,
  Sparkles,
  Copy,
  GitBranch,
} from "lucide-react";
import { generateId } from "@/lib/utils";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";
import type { Formula } from "@/lib/types";
import {
  calculateFormulaComponents,
  calculateMassBalance,
  componentsToPercent,
  compositionSimilarity,
  solveFormula,
  checkCompliance,
} from "@/lib/solver";
import {
  COMPONENT_KEYS,
  COMPONENT_LABELS,
} from "@/lib/types";
import FormulaDetailClient from "./formula-detail";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";

export default function FormulasPage() {
  return (
    <Suspense>
      <FormulasRouter />
    </Suspense>
  );
}

function FormulasRouter() {
  const searchParams = useSearchParams();
  const detailId = searchParams.get("id");

  if (detailId) {
    return <FormulaDetailClient id={detailId} />;
  }

  return <FormulasListView />;
}

function FormulasListView() {
  const { data, addFormula, addFormulas, deleteFormula } = useStore();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [newName, setNewName] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [feedbackMsg, setFeedbackMsg] = useState<{ type: "success" | "error"; text: string } | null>(null);

  function handleCreate() {
    if (!newName.trim()) return;
    const now = new Date().toISOString();
    const f: Formula = {
      id: generateId(),
      name: newName.trim(),
      description: newDesc.trim(),
      version: 1,
      targetMassG: data.targetProduct.targetMassG,
      ingredientLines: [],
      calculatedComponents: {
        water_g: 0,
        fat_g: 0,
        protein_g: 0,
        sugar_g: 0,
        starch_g: 0,
        salt_g: 0,
        hydrocolloid_g: 0,
        other_g: 0,
        total_g: 0,
      },
      massBalance: {
        totalInputG: 0,
        totalOutputG: data.targetProduct.targetMassG,
        lossG: 0,
        lossPct: 0,
        waterAdjustmentG: 0,
      },
      confidence: 0,
      notes: "",
      createdAt: now,
      updatedAt: now,
    };
    addFormula(f);
    setNewName("");
    setNewDesc("");
    setDialogOpen(false);
  }

  function handleAutoGenerate() {
    if (data.ingredients.length === 0) {
      setFeedbackMsg({ type: "error", text: "Add ingredients first before auto-generating a formula." });
      return;
    }
    setFeedbackMsg(null);
    const lines = solveFormula(
      data.targetProduct.targetMassG,
      data.targetProduct.targetComposition,
      data.ingredients
    );
    const now = new Date().toISOString();
    const f: Formula = {
      id: generateId(),
      name: `Auto-Generated #${data.formulas.length + 1}`,
      description: "Generated by the formulation solver from target composition.",
      version: 1,
      targetMassG: data.targetProduct.targetMassG,
      ingredientLines: lines,
      calculatedComponents: calculateFormulaComponents(lines, data.ingredients),
      massBalance: calculateMassBalance(lines, data.targetProduct.targetMassG),
      confidence: 0,
      notes: "Auto-generated. Review and adjust.",
      createdAt: now,
      updatedAt: now,
    };
    // Calculate composition similarity
    const calcPct = componentsToPercent(f.calculatedComponents);
    f.confidence =
      compositionSimilarity(calcPct, data.targetProduct.targetComposition) /
      100;
    addFormula(f);
  }

  function handleDelete(id: string) {
    const usedInTrials = data.trials.filter((t) => t.formulaId === id);
    const formulaName = data.formulas.find((f) => f.id === id)?.name || "this formula";
    if (usedInTrials.length > 0) {
      alert(`Cannot delete "${formulaName}" because it is referenced by ${usedInTrials.length} trial(s).\n\nDelete those trials first.`);
      return;
    }
    if (confirm(`Delete "${formulaName}"?`)) {
      deleteFormula(id);
    }
  }

  function handleDuplicate(f: Formula) {
    const now = new Date().toISOString();
    const dup: Formula = {
      ...f,
      id: generateId(),
      name: `${f.name} (copy)`,
      version: 1,
      createdAt: now,
      updatedAt: now,
    };
    addFormula(dup);
  }

  function handleCreateVariations(f: Formula) {
    if (f.ingredientLines.length === 0) {
      setFeedbackMsg({ type: "error", text: "Formula has no ingredients to vary." });
      return;
    }
    setFeedbackMsg(null);
    const now = new Date().toISOString();
    const variations = [
      { suffix: "+10%", factor: 1.1 },
      { suffix: "-10%", factor: 0.9 },
      { suffix: "random ±10%", factor: 0 },
    ];
    const newFormulas: Formula[] = variations.map((v) => {
      const lines = f.ingredientLines.map((line) => ({
        ...line,
        massG: Math.round(
          line.massG *
            (v.factor === 0
              ? 1 + (Math.random() * 0.2 - 0.1) // ±10% random
              : v.factor) *
            100
        ) / 100,
      }));
      return {
        ...f,
        id: generateId(),
        name: `${f.name} (${v.suffix})`,
        version: 1,
        ingredientLines: lines,
        calculatedComponents: calculateFormulaComponents(lines, data.ingredients),
        massBalance: calculateMassBalance(lines, f.targetMassG),
        createdAt: now,
        updatedAt: now,
      };
    });
    addFormulas(newFormulas);
  }

  // Comparison chart data
  const comparisonData = useMemo(
    () =>
      data.formulas.length > 0
        ? COMPONENT_KEYS.map((key) => {
            const row: Record<string, number | string> = {
              name: COMPONENT_LABELS[key],
              Target: data.targetProduct.targetComposition[key],
            };
            data.formulas.forEach((f) => {
              const pct = componentsToPercent(
                calculateFormulaComponents(f.ingredientLines, data.ingredients)
              );
              row[f.name] = pct[key];
            });
            return row;
          })
        : [],
    [data.formulas, data.targetProduct.targetComposition, data.ingredients]
  );

  const CHART_COLORS = [
    "#6366f1",
    "#10b981",
    "#f59e0b",
    "#ef4444",
    "#8b5cf6",
    "#ec4899",
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title="Candidate Formulas"
        subtitle={`${data.formulas.length} formula${data.formulas.length !== 1 ? "s" : ""}`}
      >
        <Button variant="outline" onClick={handleAutoGenerate}>
          <Sparkles className="h-4 w-4 mr-1" />
          Auto-Generate
        </Button>
        <Button onClick={() => setDialogOpen(true)}>
          <Plus className="h-4 w-4 mr-1" />
          New Formula
        </Button>
      </PageHeader>

      {feedbackMsg && (
        <div className={`rounded-md px-4 py-3 text-sm flex items-center justify-between ${
          feedbackMsg.type === "error"
            ? "bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300 border border-red-200 dark:border-red-800"
            : "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300 border border-green-200 dark:border-green-800"
        }`}>
          <span>{feedbackMsg.text}</span>
          <button
            onClick={() => setFeedbackMsg(null)}
            className="ml-2 hover:opacity-70"
            aria-label="Dismiss message"
          >
            ✕
          </button>
        </div>
      )}

      {/* Formula cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {data.formulas.length === 0 ? (
          <Card className="col-span-full">
            <CardContent>
              <EmptyState
                icon={<FlaskConical className="h-8 w-8" />}
                title="No formulas yet."
                subtitle="Create one manually or auto-generate from the target composition."
              />
            </CardContent>
          </Card>
        ) : (
          data.formulas.map((f) => {
            const comps = calculateFormulaComponents(
              f.ingredientLines,
              data.ingredients
            );
            const mb = calculateMassBalance(
              f.ingredientLines,
              f.targetMassG
            );
            const pct = componentsToPercent(comps);
            const sim = compositionSimilarity(
              pct,
              data.targetProduct.targetComposition
            );
            const compliance = checkCompliance(
              pct,
              data.targetProduct.targetComposition
            );

            return (
              <Card key={f.id} className="hover:border-gray-300 dark:hover:border-gray-600 transition-colors">
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <Link href={`/formulas?id=${f.id}`}>
                      <CardTitle className="text-base text-indigo-600 dark:text-indigo-400 hover:underline cursor-pointer">
                        {f.name}
                      </CardTitle>
                    </Link>
                    <div className="flex items-center gap-1">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-gray-500 dark:text-gray-400"
                        onClick={() => handleCreateVariations(f)}
                        title="Create Variations"
                        aria-label={`Create variations of ${f.name}`}
                      >
                        <GitBranch className="h-3.5 w-3.5" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-gray-500 dark:text-gray-400"
                        onClick={() => handleDuplicate(f)}
                        title="Duplicate"
                        aria-label={`Duplicate ${f.name}`}
                      >
                        <Copy className="h-3.5 w-3.5" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-red-500 dark:text-red-400"
                        onClick={() => handleDelete(f.id)}
                        aria-label={`Delete ${f.name}`}
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-2">
                  {f.description && (
                    <p className="text-xs text-gray-500 dark:text-gray-400">{f.description}</p>
                  )}
                  <div className="flex gap-2 flex-wrap">
                    <Badge variant="secondary">
                      {f.ingredientLines.length} ingredient
                      {f.ingredientLines.length !== 1 ? "s" : ""}
                    </Badge>
                    <Badge variant="secondary">
                      {mb.totalInputG.toFixed(1)} g input
                    </Badge>
                    <Badge
                      variant={sim > 80 ? "default" : "outline"}
                      title="Composition match vs target product"
                    >
                      {sim.toFixed(0)}% match
                    </Badge>
                    <Badge
                      variant={compliance.status === "compliant" ? "default" : "outline"}
                      className={
                        compliance.status === "compliant"
                          ? "bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 border-green-300 dark:border-green-700"
                          : compliance.status === "warning"
                          ? "bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 border-yellow-300 dark:border-yellow-700"
                          : "bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 border-red-300 dark:border-red-700"
                      }
                    >
                      {compliance.status === "compliant"
                        ? "✓ Compliant"
                        : compliance.status === "warning"
                        ? "⚠ Warning"
                        : "✗ Non-compliant"}
                    </Badge>
                  </div>
                  <div className="flex gap-2 text-xs text-gray-500 dark:text-gray-400">
                    <span>v{f.version}</span>
                    <span>·</span>
                    <span>
                      Confidence: {(f.confidence * 100).toFixed(0)}%
                    </span>
                  </div>
                  <Link href={`/formulas?id=${f.id}`}>
                    <Button variant="outline" size="sm" className="mt-1">
                      Open
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            );
          })
        )}
      </div>

      {/* Comparison chart */}
      {comparisonData.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">
              Formula Composition Comparison
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={comparisonData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" tick={{ fontSize: 10 }} />
                <YAxis tick={{ fontSize: 10 }} />
                <Tooltip />
                <Legend />
                <Bar dataKey="Target" fill="#94a3b8" />
                {data.formulas.map((f, idx) => (
                  <Bar
                    key={f.id}
                    dataKey={f.name}
                    fill={CHART_COLORS[idx % CHART_COLORS.length]}
                  />
                ))}
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      )}

      {/* Create dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>New Formula</DialogTitle>
            <DialogDescription>
              Create a new candidate formula. You can add ingredients in the
              detail view.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Name</Label>
              <Input
                value={newName}
                onChange={(e) => setNewName(e.target.value)}
                placeholder="e.g. Candidate B – Low fat"
              />
            </div>
            <div className="space-y-2">
              <Label>Description</Label>
              <Textarea
                value={newDesc}
                onChange={(e) => setNewDesc(e.target.value)}
                placeholder="Describe the approach..."
                rows={2}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleCreate} disabled={!newName.trim()}>Create</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
